name: GithubAction
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Define env name'   
        required: true
        default: 'prod'
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: approvers
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Print user input
        run: |
          echo "Env: ${{ github.event.inputs.env }}"
